
package firstprojecthotelmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Create_Room11 extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement st = null;
   
    public Create_Room11() {
        initComponents();
         showRooms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RNameTb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categorycb = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Statuscb = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        priceTb = new javax.swing.JTextField();
        AbbBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomsList = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Manage Rooms");

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(467, 467, 467)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Room code");

        rcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcodeActionPerformed(evt);
            }
        });

        jLabel5.setText("Room Name");

        jLabel6.setText("Category");

        categorycb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        categorycb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Family", "Vip" }));
        categorycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorycbActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        Statuscb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free", "Booked" }));
        Statuscb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StatuscbItemStateChanged(evt);
            }
        });

        jLabel8.setText("Price");

        AbbBtn.setText("Add Room");
        AbbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbbBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Update");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        RoomsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Room code", "Room Name", "Type", "Status", "Price"
            }
        ));
        RoomsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RoomsList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rcode)
                            .addComponent(RNameTb)
                            .addComponent(categorycb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Statuscb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceTb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(AbbBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(RNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categorycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Statuscb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteBtn)
                            .addComponent(AbbBtn)
                            .addComponent(EditBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void rcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcodeActionPerformed

    private void categorycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorycbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorycbActionPerformed

    private void StatuscbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StatuscbItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_StatuscbItemStateChanged

      int rid;
    
      private void showRooms() {
        model = new DefaultTableModel();

        model.addColumn("Serial No");//Number=model table column name
        model.addColumn("Room code");
        model.addColumn("Room Name");
        model.addColumn("Type");
        model.addColumn("Status");
        model.addColumn("Price");
        String sql = "select * from Room";

        try {
            Connection con = DatabaseConnection.getDBConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {

                String id = rs.getString("Rnum"); //Rnum=sql table column name
                String code = rs.getString("Rcode");
                String name = rs.getString("RName");
                String category = rs.getString("RType");
                String status = rs.getString("RStatus");
                String price = rs.getString("Price");

                Object[] rowData = {id,code, name, category, status, price};
                model.addRow(rowData);

            }
            RoomsList.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
    
  
     
  
    
    
      
      
    
    private void AbbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbbBtnActionPerformed
        // TODO add your handling code here:

            if (RNameTb.getText().isEmpty() || categorycb.getSelectedIndex() == -1 || Statuscb.getSelectedIndex() == -1 || priceTb.getText().isEmpty() || rcode.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Missing input Data");

        } else {
            try {
              // countroom();
               int num = 0;
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "root");

                PreparedStatement save = con.prepareStatement("insert into Room values (?,?,?,?,?,?)");

                save.setInt(1, num);
                 save.setInt(2, Integer.valueOf(rcode.getText().toString()));
                save.setString(3, RNameTb.getText().toString());
                save.setString(4, categorycb.getSelectedItem().toString());
                save.setString(5, Statuscb.getSelectedItem().toString());
                save.setInt(6, Integer.valueOf(priceTb.getText().toString()));

                int row = save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Room added Successfully");
                con.close();

                showRooms();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);
            }

        }

        
    }//GEN-LAST:event_AbbBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
 
       if (rcode.getText().isEmpty() ||  RNameTb.getText().isEmpty() || priceTb.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Missing input Data");

        } else {

            String sql = "update room set  Rcode=?, Rname = ?, RType = ?, RStatus = ?, Price = ? where Rnum = ?";
            try {
                // int Rnum = 0;
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "root");

                PreparedStatement save = con.prepareStatement(sql);
                
               save.setInt(1, Integer.valueOf(rcode.getText().toString()));
                save.setString(2, RNameTb.getText().toString());
                 
                save.setString(3, categorycb.getSelectedItem().toString());
                save.setString(4, Statuscb.getSelectedItem().toString());
                save.setInt(5, Integer.valueOf(priceTb.getText().toString()));
                save.setInt(6, key);
                int row = save.executeUpdate();

                JOptionPane.showMessageDialog(this, "Room updated Successfully");
                con.close();

                showRooms();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_EditBtnActionPerformed

      int key = 0;
    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:

        if (key == 0) {

            JOptionPane.showMessageDialog(this, "Select a Room");

        } else {
            try {
                // int Rnum = 0;
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "root");

                PreparedStatement save = con.prepareStatement("Delete from Room where Rnum =?");

                save.setInt(1, key);

                int row = save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Room Deleted Successfully");
                con.close();

                showRooms();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e);
            }

        }

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void RoomsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsListMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) RoomsList.getModel();
        int MyIndex = RoomsList.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());

        rcode.setText(model.getValueAt(MyIndex, 1).toString());
        RNameTb.setText(model.getValueAt(MyIndex, 2).toString());
        categorycb.setSelectedItem(model.getValueAt(MyIndex, 3));
        Statuscb.setSelectedItem(model.getValueAt(MyIndex, 4));
        priceTb.setText(model.getValueAt(MyIndex, 5).toString());

    }//GEN-LAST:event_RoomsListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Room11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Room11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Room11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Room11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Room11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbbBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField RNameTb;
    private javax.swing.JTable RoomsList;
    private javax.swing.JComboBox Statuscb;
    private javax.swing.JComboBox categorycb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceTb;
    private javax.swing.JTextField rcode;
    // End of variables declaration//GEN-END:variables
}
